# Generated by Django 5.2.8 on 2025-11-06 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoTomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prestamo', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_prestamo', models.DateField(blank=True, null=True)),
                ('hora_prestamo', models.TimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('hora_devolucion', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Préstamo de Tomo',
                'verbose_name_plural': 'Préstamos de Tomos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=9)),
                ('rol_solicitud', models.CharField(choices=[('solicitante', 'Solicitante'), ('prestante', 'Prestante')], default='solicitante', max_length=11)),
                ('codigo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.prestamotomo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamos',
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_detalle_tomo', models.CharField(choices=[('pendiente', 'Pendiente'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=9)),
                ('tomo_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.asignaciontomo')),
                ('codigo_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.prestamotomo')),
            ],
            options={
                'verbose_name': 'Detalle de Préstamo',
                'verbose_name_plural': 'Detalles de Préstamo',
                'constraints': [models.UniqueConstraint(fields=('tomo_solicitado', 'codigo_prestamo'), name='unique_tomo_solicitado_codigo_prestamo')],
            },
        ),
    ]
