# Generated by Django 5.2.8 on 2025-11-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('archivos', '0001_initial'),
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('hora_asigancion', models.TimeField(auto_now_add=True)),
                ('cantidad_asignacion', models.SmallIntegerField(default=1)),
                ('espacio_ocupado', models.SmallIntegerField(default=5)),
                ('estante_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.nivelestante')),
                ('material_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Asignación de Material',
                'verbose_name_plural': 'Asignaciones de Materiales',
                'constraints': [models.UniqueConstraint(fields=('estante_almacen', 'material_asignado'), name='unique_estante_almacen_material')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('hora_asigancion', models.TimeField(auto_now_add=True)),
                ('estado_tomo', models.CharField(default='disponible', max_length=10)),
                ('espacio_ocupado', models.SmallIntegerField(default=5)),
                ('estante_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.nivelestante')),
                ('tomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.tomo')),
            ],
            options={
                'verbose_name': 'Asignación de Tomo',
                'verbose_name_plural': 'Asignaciones de Tomos',
                'constraints': [models.UniqueConstraint(fields=('estante_almacen', 'tomo'), name='unique_estante_almacen_tomo')],
            },
        ),
    ]
