# Generated by Django 6.0 on 2025-12-04 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_almacen', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=5)),
                ('categoria', models.CharField(max_length=75)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'constraints': [models.UniqueConstraint(fields=('partida', 'categoria'), name='unique_partida_categoria')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=14)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('cantidad_minima', models.PositiveSmallIntegerField(default=1)),
                ('cantidad_existente', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('unidad_ingreso', models.CharField(max_length=35)),
                ('cantidad_x_unidad_ingreso', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('volumen', models.CharField(default='N/A', max_length=25)),
                ('unidad_salida', models.CharField(max_length=35)),
                ('tipo_material', models.CharField(max_length=25)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.partidapresupuestaria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'nit'), name='unique_proveedor_nit')],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ingreso', models.CharField(max_length=10, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('factura', models.CharField(max_length=10)),
                ('h_ruta', models.CharField(max_length=25)),
                ('orden_compra', models.CharField(max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.proveedor')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='IngresoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.ingreso')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Material Ingresado',
                'verbose_name_plural': 'Materiales Ingresados',
                'constraints': [models.UniqueConstraint(fields=('material', 'ingreso'), name='unique_material_ingreso')],
            },
        ),
    ]
