# Generated by Django 5.2.8 on 2025-11-11 12:54

import apps.archivos.functions.guardar_carpeta
import apps.archivos.functions.validar_pdf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_tomo', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=75)),
                ('glosa', models.TextField()),
                ('gestion', models.CharField(blank=True, max_length=4, null=True)),
                ('mes', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_apertura', models.DateField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='activo', max_length=7)),
                ('nro_fojas_total', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Tomo',
                'verbose_name_plural': 'Tomos',
                'constraints': [models.UniqueConstraint(fields=('nro_tomo', 'titulo'), name='unique_nro_tomo_titulo')],
            },
        ),
        migrations.CreateModel(
            name='DetalleTomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_doc', models.SmallIntegerField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('fecha_adjunto', models.DateTimeField(auto_now_add=True)),
                ('nro_fojas', models.SmallIntegerField(blank=True, null=True)),
                ('estado_archivo', models.CharField(blank=True, choices=[('adjunto', 'Adjunto'), ('no adjunto', 'No Adjunto')], max_length=10, null=True)),
                ('archivo', models.FileField(blank=True, upload_to=apps.archivos.functions.guardar_carpeta.get_upload_to, validators=[apps.archivos.functions.validar_pdf.validate_pdf])),
                ('tomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.tomo')),
            ],
            options={
                'verbose_name': 'Detalle de Tomo',
                'verbose_name_plural': 'Detalles de Tomo',
                'constraints': [models.UniqueConstraint(fields=('nro_doc', 'tomo'), name='unique_nro_doc_tomo')],
            },
        ),
    ]
