# Generated by Django 5.2.8 on 2025-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletomo',
            name='nro_doc',
            field=models.SmallIntegerField(),
        ),
    ]
