# Generated by Django 5.2.8 on 2025-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_detalletomo_nro_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletomo',
            name='nro_doc',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
