# Generated by Django 5.2.8 on 2025-11-06 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['nombre', 'apellido_paterno'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
