# Generated by Django 6.0 on 2025-12-04 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitud', models.CharField(max_length=5, unique=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('hora_solicitud', models.TimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobada', 'aprobada'), ('rechazada', 'rechazada'), ('finalizada', 'finalizada')], default='pendiente', max_length=10)),
                ('observación', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dirigido_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Solicitud de Material',
                'verbose_name_plural': 'Solicitud de Materiales',
            },
        ),
        migrations.CreateModel(
            name='EntregaMaterialSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('material_entregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudmaterial')),
            ],
            options={
                'verbose_name': 'Entrega de Material Solicitado',
                'verbose_name_plural': 'Entregas de Materiales Solicitados',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveSmallIntegerField(default=1)),
                ('estado_detalle', models.CharField(choices=[('reservado', 'reservado'), ('entregado', 'entregado')], default='reservado', max_length=9)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudmaterial')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Material',
                'verbose_name_plural': 'Detalles de Solicitud de Material',
                'constraints': [models.UniqueConstraint(fields=('material', 'solicitud'), name='unique_material_solicitud')],
            },
        ),
    ]
