# Generated by Django 5.2.8 on 2025-11-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nivel', models.SmallIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_almacen', models.SmallIntegerField()),
                ('tipo_almacen', models.CharField(choices=[('material', 'Material'), ('archivos', 'Archivos')], max_length=8)),
                ('ubicacion', models.TextField()),
                ('estado_almacen', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'constraints': [models.UniqueConstraint(fields=('nro_almacen', 'tipo_almacen'), name='unique_nro_almacen_tipo_almacen')],
            },
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_estante', models.SmallIntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
            ],
            options={
                'verbose_name': 'Estante',
                'verbose_name_plural': 'Estantes',
            },
        ),
        migrations.CreateModel(
            name='NivelEstante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio_disponible', models.SmallIntegerField(default=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.estante')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.nivel')),
            ],
            options={
                'verbose_name': 'Niveles de Estante',
            },
        ),
        migrations.AddConstraint(
            model_name='estante',
            constraint=models.UniqueConstraint(fields=('nro_estante', 'almacen'), name='unique_almacen_estante_descripcion_estante'),
        ),
        migrations.AddConstraint(
            model_name='nivelestante',
            constraint=models.UniqueConstraint(fields=('estante', 'nivel'), name='unique_estante_nivel'),
        ),
    ]
